### ISSUE TITLE
clarify _flush() functionality in serialport context

### ISSUE THREAD

**Issue by RafaelKa** [RafaelKa/node-serialport-enocean-parser#30]
We must evaluate functionality of _flush() properly.
https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/ESP3Parser.js#L151-L155

- [x] Is it possible, that not fulfilled Packet will be pushed, if _flush() is called?
- [x] Is it possible, that the same Packet can be emitted twice? Also for example if _flush() is called in same tick with emitFetchedESP3Packet().

Something else is important?

**Comment by Holger-Will** [comment]
"Custom Transform implementations may implement the transform._flush() method. This will be called when there is no more written data to be consumed, but before the 'end' event is emitted signaling the end of the Readable stream.
The transform._flush() method is prefixed with an underscore because it is internal to the class that defines it, and should never be called directly by user programs."
https://nodejs.org/api/stream.html#stream_transform_flush_callback

**Comment by Holger-Will** [comment]
Is it possible, that not fulfilled Packet will be pushed, if _flush() is called?

no, because we are the only ones calling it. especially

**Comment by Holger-Will** [comment]
tracking bug #12
